spring.application.name=lunail-api
spring.datasource.url=jdbc:postgresql://localhost:5432/lunail
spring.datasource.username=clara
spring.datasource.password=cislok1999
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
